package com.fly.model;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ID
     *
     * @mbg.generated Sun Feb 19 20:43:10 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.USER_NAME
     *
     * @mbg.generated Sun Feb 19 20:43:10 CST 2017
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.PASSWORD
     *
     * @mbg.generated Sun Feb 19 20:43:10 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.LANGUAGE
     *
     * @mbg.generated Sun Feb 19 20:43:10 CST 2017
     */
    private String language;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.EMAIL
     *
     * @mbg.generated Sun Feb 19 20:43:10 CST 2017
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.CREATE_TIME
     *
     * @mbg.generated Sun Feb 19 20:43:10 CST 2017
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.UPDATE_TIME
     *
     * @mbg.generated Sun Feb 19 20:43:10 CST 2017
     */
    private String updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.MOBILE
     *
     * @mbg.generated Sun Feb 19 20:43:10 CST 2017
     */
    private String mobile;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ID
     *
     * @return the value of user.ID
     *
     * @mbg.generated Sun Feb 19 20:43:10 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ID
     *
     * @param id the value for user.ID
     *
     * @mbg.generated Sun Feb 19 20:43:10 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.USER_NAME
     *
     * @return the value of user.USER_NAME
     *
     * @mbg.generated Sun Feb 19 20:43:10 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.USER_NAME
     *
     * @param userName the value for user.USER_NAME
     *
     * @mbg.generated Sun Feb 19 20:43:10 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.PASSWORD
     *
     * @return the value of user.PASSWORD
     *
     * @mbg.generated Sun Feb 19 20:43:10 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.PASSWORD
     *
     * @param password the value for user.PASSWORD
     *
     * @mbg.generated Sun Feb 19 20:43:10 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.LANGUAGE
     *
     * @return the value of user.LANGUAGE
     *
     * @mbg.generated Sun Feb 19 20:43:10 CST 2017
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.LANGUAGE
     *
     * @param language the value for user.LANGUAGE
     *
     * @mbg.generated Sun Feb 19 20:43:10 CST 2017
     */
    public void setLanguage(String language) {
        this.language = language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.EMAIL
     *
     * @return the value of user.EMAIL
     *
     * @mbg.generated Sun Feb 19 20:43:10 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.EMAIL
     *
     * @param email the value for user.EMAIL
     *
     * @mbg.generated Sun Feb 19 20:43:10 CST 2017
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.CREATE_TIME
     *
     * @return the value of user.CREATE_TIME
     *
     * @mbg.generated Sun Feb 19 20:43:10 CST 2017
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.CREATE_TIME
     *
     * @param createTime the value for user.CREATE_TIME
     *
     * @mbg.generated Sun Feb 19 20:43:10 CST 2017
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.UPDATE_TIME
     *
     * @return the value of user.UPDATE_TIME
     *
     * @mbg.generated Sun Feb 19 20:43:10 CST 2017
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.UPDATE_TIME
     *
     * @param updateTime the value for user.UPDATE_TIME
     *
     * @mbg.generated Sun Feb 19 20:43:10 CST 2017
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.MOBILE
     *
     * @return the value of user.MOBILE
     *
     * @mbg.generated Sun Feb 19 20:43:10 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.MOBILE
     *
     * @param mobile the value for user.MOBILE
     *
     * @mbg.generated Sun Feb 19 20:43:10 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
}