package com.fly.model;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ID
     *
     * @mbg.generated Tue Feb 21 23:36:59 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.USER_NAME
     *
     * @mbg.generated Tue Feb 21 23:36:59 CST 2017
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.PASSWORD
     *
     * @mbg.generated Tue Feb 21 23:36:59 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.NICK_NAME
     *
     * @mbg.generated Tue Feb 21 23:36:59 CST 2017
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.SEX
     *
     * @mbg.generated Tue Feb 21 23:36:59 CST 2017
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.MOBILE
     *
     * @mbg.generated Tue Feb 21 23:36:59 CST 2017
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.SIGNATURE
     *
     * @mbg.generated Tue Feb 21 23:36:59 CST 2017
     */
    private String signature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.CITY
     *
     * @mbg.generated Tue Feb 21 23:36:59 CST 2017
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.KISS_NUMBER
     *
     * @mbg.generated Tue Feb 21 23:36:59 CST 2017
     */
    private Integer kissNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.HEAD_IMAGE
     *
     * @mbg.generated Tue Feb 21 23:36:59 CST 2017
     */
    private String headImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.LANGUAGE
     *
     * @mbg.generated Tue Feb 21 23:36:59 CST 2017
     */
    private String language;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.CREATE_TIME
     *
     * @mbg.generated Tue Feb 21 23:36:59 CST 2017
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.LAST_MODIFY_TIME
     *
     * @mbg.generated Tue Feb 21 23:36:59 CST 2017
     */
    private String lastModifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ID
     *
     * @return the value of user.ID
     *
     * @mbg.generated Tue Feb 21 23:36:59 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ID
     *
     * @param id the value for user.ID
     *
     * @mbg.generated Tue Feb 21 23:36:59 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.USER_NAME
     *
     * @return the value of user.USER_NAME
     *
     * @mbg.generated Tue Feb 21 23:36:59 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.USER_NAME
     *
     * @param userName the value for user.USER_NAME
     *
     * @mbg.generated Tue Feb 21 23:36:59 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.PASSWORD
     *
     * @return the value of user.PASSWORD
     *
     * @mbg.generated Tue Feb 21 23:36:59 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.PASSWORD
     *
     * @param password the value for user.PASSWORD
     *
     * @mbg.generated Tue Feb 21 23:36:59 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.NICK_NAME
     *
     * @return the value of user.NICK_NAME
     *
     * @mbg.generated Tue Feb 21 23:36:59 CST 2017
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.NICK_NAME
     *
     * @param nickName the value for user.NICK_NAME
     * @mbg.generated Tue Feb 21 23:36:59 CST 2017
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.SEX
     *
     * @return the value of user.SEX
     * @mbg.generated Tue Feb 21 23:36:59 CST 2017
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.SEX
     *
     * @param sex the value for user.SEX
     * @mbg.generated Tue Feb 21 23:36:59 CST 2017
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.MOBILE
     *
     * @return the value of user.MOBILE
     * @mbg.generated Tue Feb 21 23:36:59 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.MOBILE
     *
     * @param mobile the value for user.MOBILE
     * @mbg.generated Tue Feb 21 23:36:59 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.SIGNATURE
     *
     * @return the value of user.SIGNATURE
     * @mbg.generated Tue Feb 21 23:36:59 CST 2017
     */
    public String getSignature() {
        return signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.SIGNATURE
     *
     * @param signature the value for user.SIGNATURE
     * @mbg.generated Tue Feb 21 23:36:59 CST 2017
     */
    public void setSignature(String signature) {
        this.signature = signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.CITY
     *
     * @return the value of user.CITY
     * @mbg.generated Tue Feb 21 23:36:59 CST 2017
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.CITY
     *
     * @param city the value for user.CITY
     * @mbg.generated Tue Feb 21 23:36:59 CST 2017
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.KISS_NUMBER
     *
     * @return the value of user.KISS_NUMBER
     * @mbg.generated Tue Feb 21 23:36:59 CST 2017
     */
    public Integer getKissNumber() {
        return kissNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.KISS_NUMBER
     *
     * @param kissNumber the value for user.KISS_NUMBER
     * @mbg.generated Tue Feb 21 23:36:59 CST 2017
     */
    public void setKissNumber(Integer kissNumber) {
        this.kissNumber = kissNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.HEAD_IMAGE
     *
     * @return the value of user.HEAD_IMAGE
     * @mbg.generated Tue Feb 21 23:36:59 CST 2017
     */
    public String getHeadImage() {
        return headImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.HEAD_IMAGE
     *
     * @param headImage the value for user.HEAD_IMAGE
     * @mbg.generated Tue Feb 21 23:36:59 CST 2017
     */
    public void setHeadImage(String headImage) {
        this.headImage = headImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.LANGUAGE
     *
     * @return the value of user.LANGUAGE
     *
     * @mbg.generated Tue Feb 21 23:36:59 CST 2017
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.LANGUAGE
     *
     * @param language the value for user.LANGUAGE
     *
     * @mbg.generated Tue Feb 21 23:36:59 CST 2017
     */
    public void setLanguage(String language) {
        this.language = language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.CREATE_TIME
     *
     * @return the value of user.CREATE_TIME
     *
     * @mbg.generated Tue Feb 21 23:36:59 CST 2017
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.CREATE_TIME
     *
     * @param createTime the value for user.CREATE_TIME
     *
     * @mbg.generated Tue Feb 21 23:36:59 CST 2017
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.LAST_MODIFY_TIME
     *
     * @return the value of user.LAST_MODIFY_TIME
     *
     * @mbg.generated Tue Feb 21 23:36:59 CST 2017
     */
    public String getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.LAST_MODIFY_TIME
     *
     * @param lastModifyTime the value for user.LAST_MODIFY_TIME
     * @mbg.generated Tue Feb 21 23:36:59 CST 2017
     */
    public void setLastModifyTime(String lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }
}